import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { getUpcomingEvents } from "@/lib/google-api";
import prisma from "@/lib/prisma";
import { generateMorningBrief } from "@/lib/gemini";
import { Resend } from "resend";

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

export async function GET() {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email || !(session as any).accessToken) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    try {
        const user = await prisma.user.findUnique({
            where: { email: session.user.email },
        });

        if (!user) {
            return NextResponse.json({ error: "User not found" }, { status: 404 });
        }

        // 1. Fetch Today's Events
        const events = await getUpcomingEvents((session as any).accessToken, 10);
        const today = new Date().toDateString();
        const todayEvents = events.filter((e: any) => 
            new Date(e.start.dateTime || e.start.date).toDateString() === today
        );

        // 2. Fetch Pending Action Items
        const actionItems = await prisma.actionItem.findMany({
            where: { 
                userId: user.id,
                status: "PENDING"
            },
            orderBy: { priority: "desc" }
        });

        // 3. Generate Brief with Gemini
        const briefMarkdown = await generateMorningBrief(user.name || "User", todayEvents, actionItems);

        // 4. Send Email (Optional if API Key exists)
        let emailSent = false;
        if (resend && process.env.RESEND_API_KEY) {
            try {
                await resend.emails.send({
                    from: "Vela AI <onboarding@resend.dev>",
                    to: session.user.email,
                    subject: `☀️ Your Morning Briefing - ${new Date().toLocaleDateString()}`,
                    html: `
                        <div style="font-family: sans-serif; color: #333; max-width: 600px; margin: 0 auto; line-height: 1.6;">
                            <h2 style="color: #6c63ff;">Good Morning, ${user.name || 'User'}!</h2>
                            <div style="background: #f9fafb; padding: 20px; border-radius: 12px; border: 1px solid #e5e7eb;">
                                ${briefMarkdown.replace(/\n/g, '<br/>')}
                            </div>
                            <p style="font-size: 0.8rem; color: #9ca3af; margin-top: 20px; text-align: center;">
                                This brief was generated by Vela AI based on your schedule and tasks.
                            </p>
                        </div>
                    `
                });
                emailSent = true;
            } catch (emailError) {
                console.error("Failed to send email via Resend:", emailError);
            }
        }

        return NextResponse.json({
            success: true,
            brief: briefMarkdown,
            emailSent,
            message: emailSent ? "Briefing sent to your email!" : "Briefing generated (Email skipped: Missing RESEND_API_KEY)"
        });

    } catch (error) {
        console.error("Failed to generate morning brief:", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}
